#Generated by Nebulirion.

execute if predicate ut:recipes/ut_dog1 run data modify storage utstats:main LoadedPlayer.Recipes.ut_dog1 set value 1b
execute if predicate ut:recipes/ut_dog10 run data modify storage utstats:main LoadedPlayer.Recipes.ut_dog10 set value 1b
execute if predicate ut:recipes/ut_dog11 run data modify storage utstats:main LoadedPlayer.Recipes.ut_dog11 set value 1b
execute if predicate ut:recipes/ut_dog12 run data modify storage utstats:main LoadedPlayer.Recipes.ut_dog12 set value 1b
execute if predicate ut:recipes/ut_dog13 run data modify storage utstats:main LoadedPlayer.Recipes.ut_dog13 set value 1b
execute if predicate ut:recipes/ut_dog14 run data modify storage utstats:main LoadedPlayer.Recipes.ut_dog14 set value 1b
execute if predicate ut:recipes/ut_dog15 run data modify storage utstats:main LoadedPlayer.Recipes.ut_dog15 set value 1b
execute if predicate ut:recipes/ut_dog16 run data modify storage utstats:main LoadedPlayer.Recipes.ut_dog16 set value 1b
execute if predicate ut:recipes/ut_dog17 run data modify storage utstats:main LoadedPlayer.Recipes.ut_dog17 set value 1b
execute if predicate ut:recipes/ut_dog18 run data modify storage utstats:main LoadedPlayer.Recipes.ut_dog18 set value 1b
execute if predicate ut:recipes/ut_dog19 run data modify storage utstats:main LoadedPlayer.Recipes.ut_dog19 set value 1b
execute if predicate ut:recipes/ut_dog2 run data modify storage utstats:main LoadedPlayer.Recipes.ut_dog2 set value 1b
execute if predicate ut:recipes/ut_dog3 run data modify storage utstats:main LoadedPlayer.Recipes.ut_dog3 set value 1b
execute if predicate ut:recipes/ut_dog4 run data modify storage utstats:main LoadedPlayer.Recipes.ut_dog4 set value 1b
execute if predicate ut:recipes/ut_dog5 run data modify storage utstats:main LoadedPlayer.Recipes.ut_dog5 set value 1b
execute if predicate ut:recipes/ut_dog6 run data modify storage utstats:main LoadedPlayer.Recipes.ut_dog6 set value 1b
execute if predicate ut:recipes/ut_dog7 run data modify storage utstats:main LoadedPlayer.Recipes.ut_dog7 set value 1b
execute if predicate ut:recipes/ut_dog8 run data modify storage utstats:main LoadedPlayer.Recipes.ut_dog8 set value 1b
execute if predicate ut:recipes/ut_dog9 run data modify storage utstats:main LoadedPlayer.Recipes.ut_dog9 set value 1b
execute if predicate ut:recipes/ut_timer1 run data modify storage utstats:main LoadedPlayer.Recipes.ut_timer1 set value 1b
execute if predicate ut:recipes/ut_timer2 run data modify storage utstats:main LoadedPlayer.Recipes.ut_timer2 set value 1b
execute if predicate ut:recipes/ut_timer3 run data modify storage utstats:main LoadedPlayer.Recipes.ut_timer3 set value 1b
execute if predicate ut:recipes/ut_timer4 run data modify storage utstats:main LoadedPlayer.Recipes.ut_timer4 set value 1b
execute if predicate ut:recipes/ut_timer5 run data modify storage utstats:main LoadedPlayer.Recipes.ut_timer5 set value 1b
